back/photography/urls.py
from django.urls import path

from . import views

app_name = 'photography'
urlpatterns = [
    path('', views.index, name='index'),
    path('camera/<int:camera_id>/', views.camera, name="camera"),
    path('film/<int:film_id>/', views.film, name="film"),
]

back/shutter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from . import views

urlpatterns = [
    path('photography/', include('photography.urls')),
    path('cinematography/', include('cinematography.urls')),
    path('admin/', admin.site.urls),
    path('', views.index),
]

cinematography/urls.py
from django.urls import path

from . import views

app_name = 'cinematography'
urlpatterns = [
    path('', views.index, name='index'),
    path('camera/<int:camera_id>/', views.camera, name="camera"),
    path('film/<int:film_id>/', views.film, name="film"),
]

photography/urls.py
from django.urls import path
from . import views

app_name = 'photography'
urlpatterns = [
    path('', views.index, name='index'),
    path('camera/<int:camera_id>/', views.camera, name="camera"),
    path('film/<int:film_id>/', views.film, name="film"),
]

shutter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from . import views

urlpatterns = [
    path('photography/', include('photography.urls')),
    path('cinematography/', include('cinematography.urls')),
    path('admin/', admin.site.urls),
    path('', views.index)
]

back/cinematography/models.py
from pyexpat import model
from unicodedata import name
from django.db import models

class Camera(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    lens_mount = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

class Film(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    iso = models.DecimalField(max_digits=1000, decimal_places=0)
    exposures = models.DecimalField(max_digits=1000, decimal_places=0)
    number_of_rolls = models.DecimalField(max_digits=10, decimal_places=0)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

back/photography/models.py
from pyexpat import model
from unicodedata import name
from django.db import models

class Camera(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    lens_mount = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

class Film(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    iso = models.DecimalField(max_digits=1000, decimal_places=0)
    exposures = models.DecimalField(max_digits=1000, decimal_places=0)
    number_of_rolls = models.DecimalField(max_digits=10, decimal_places=0)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

cinematography/models.py
from pyexpat import model
from unicodedata import name
from django.db import models

class Camera(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    lens_mount = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

class Film(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    iso = models.DecimalField(max_digits=1000, decimal_places=0)
    exposures = models.DecimalField(max_digits=1000, decimal_places=0)
    number_of_rolls = models.DecimalField(max_digits=10, decimal_places=0)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

photography/models.py
from pyexpat import model
from unicodedata import name
from django.db import models

class Camera(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    lens_mount = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

class Film(models.Model):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    format = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    iso = models.DecimalField(max_digits=1000, decimal_places=0)
    exposures = models.DecimalField(max_digits=1000, decimal_places=0)
    number_of_rolls = models.DecimalField(max_digits=10, decimal_places=0)
    price = models.DecimalField(max_digits=1000, decimal_places=2)

cinematography/views.py
from django.http import HttpResponse
from .models import *
from django.shortcuts import render, get_object_or_404


def index(request):
    latest_film_list = Film.objects.order_by('id')
    latest_camera_list = Camera.objects.order_by('id')
    context = {'latest_film_list': latest_film_list, 'latest_camera_list': latest_camera_list}
    return render(request, 'cinematography/index.html', context)


def camera(request, camera_id):
    camera = Camera.objects.get(pk=camera_id)
    context = {'camera': camera}
    return render(request, 'cinematography/camera.html', context)



def film(request, film_id):
    film = Film.objects.get(pk=film_id)
    context = {'film': film}
    return render(request, 'cinematography/film.html', context)

photography/views.py
from django.http import HttpResponse
from .models import *
from django.shortcuts import render, get_object_or_404


def index(request):
    latest_film_list = Film.objects.order_by('id')
    latest_camera_list = Camera.objects.order_by('id')
    context = {'latest_film_list': latest_film_list, 'latest_camera_list': latest_camera_list}
    return render(request, 'photography/index.html', context)


def camera(request, camera_id):
    camera = Camera.objects.get(pk=camera_id)
    context = {'camera': camera}
    return render(request, 'photography/camera.html', context)



def film(request, film_id):
    film = Film.objects.get(pk=film_id)
    context = {'film': film}
    return render(request, 'photography/film.html', context)

shutter/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

cinematography/templates/cinematography/camera.html
{% if camera %}
    <p>Name: {{ camera.name }}</p>
    <p>Company: {{ camera.company }}</p>
    <p>Format: {{ camera.format }}</p>
    <p>Lens Mount: {{ camera.lens_mount }}</p>
    <p>Price: {{ camera.price }}</p>
{% else %}
    <p>ERROR</p>
{% endif %}

cinematography/templates/cinematography/film.html
{% if film %}
    <p>Name: {{ film.name }}</p>
    <p>Company: {{ film.company }}</p>
    <p>Format: {{ film.format }}</p>
    <p>Type: {{ film.type}} </p>
    <p>ISO: {{ film.iso }} </p>
    <p>Exposures: {{ film.exposures }} </p>
    <p>Number of Rolls: {{ film.number_of_rolls}} </p>
    <p>Price: {{ film.price }}</p>
{% else %}
    <p>ERROR</p>
{% endif %}

cinematography/templates/cinematography/index.html
<h1>Films</h1>
{% if latest_film_list %}
    <table>
        <tr>
            <th>Name</th>
            <th>Company</th>
            <th>More info</th>
        </tr>
    {% for film in latest_film_list %}
        <tr>
            <td>{{ film.name }}</td>
            <td>{{ film.company }}</td>
            <td><a href="{% url 'cinematography:film' film.id %}">Click</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No films are available</p>
{% endif %}


<h1>Cameras</h1>
{% if latest_camera_list %}
    <table>
        <tr>
            <th>Name</th>
            <th>Company</th>
            <th>More info</th>
        </tr>
    {% for camera in latest_camera_list %}
        <tr>
            <td>{{ camera.name }}</td>
            <td>{{ camera.company }}</td>
            <td><a href="{% url 'cinematography:camera' camera.id %}">Click</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No cameras are available</p>
{% endif %}

photography/templates/photography/camera.html
{% if camera %}
    <p>Name: {{ camera.name }}</p>
    <p>Company: {{ camera.company }}</p>
    <p>Format: {{ camera.format }}</p>
    <p>Lens Mount: {{ camera.lens_mount }}</p>
    <p>Price: {{ camera.price }}</p>
{% else %}
    <p>ERROR</p>
{% endif %}

photography/templates/photography/film.html
{% if film %}
    <p>Name: {{ film.name }}</p>
    <p>Company: {{ film.company }}</p>
    <p>Format: {{ film.format }}</p>
    <p>Type: {{ film.type}} </p>
    <p>ISO: {{ film.iso }} </p>
    <p>Exposures: {{ film.exposures }} </p>
    <p>Number of Rolls: {{ film.number_of_rolls}} </p>
    <p>Price: {{ film.price }}</p>
{% else %}
    <p>ERROR</p>
{% endif %}

photography/templates/photography/index.html
<h1>Films</h1>
{% if latest_film_list %}
    <table>
        <tr>
            <th>Name</th>
            <th>Company</th>
            <th>More info</th>
        </tr>
    {% for film in latest_film_list %}
        <tr>
            <td>{{ film.name }}</td>
            <td>{{ film.company }}</td>
            <td><a href="{% url 'photography:film' film.id %}">Click</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No films are available</p>
{% endif %}


<h1>Cameras</h1>
{% if latest_camera_list %}
    <table>
        <tr>
            <th>Name</th>
            <th>Company</th>
            <th>More info</th>
        </tr>
    {% for camera in latest_camera_list %}
        <tr>
            <td>{{ camera.name }}</td>
            <td>{{ camera.company }}</td>
            <td><a href="{% url 'photography:camera' camera.id %}">Click</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No cameras are available</p>
{% endif %}

templates/index.html
<h1>Home Page</h1>
<a href="/photography">Photography Section</a>
<a href="/cinematography">Cinematography Section</a>